import type { NextPage } from 'next';
import Image from '../components/Image';
import HtmlHead from '../components/HtmlHead';

const MainFrame: NextPage = () => {
  return (
    <>
      <HtmlHead title="Home" description="Generated by create next app" />
      <Home />
    </>
  );
};

const Home = () => {
  return (
    <>
      <div className="w-4/5 lg:w-5/6 mx-auto mt-8">
        <div className="flex flex-col items-center space-y-8 md:space-y-16 md:grid grid-cols-2 lg:w-5/6 mx-auto">
          <div className="space-y-2 md:space-y-6">
            <p className="text-6xl lg:text-7xl xl:text-8xl alegreya-font">
              Hi, I&apos;m Leo
            </p>
            <p className="text-sm md:text-lg ml-1">
              a Software Engineer, Basketball Enthusiast, CSGO Tactician
            </p>
          </div>

          <div className="flex flex-col items-center justify-center space-y-8">
            <Image
              src="/img/Fushimi_railway.jpg"
              alt="Icon"
              width={240}
              height={240}
              className="rounded-full"
            />
            <div className="text-lg md:text-xl lg:text-2xl">
              <em>Stepping out of comfort zone</em>
            </div>
          </div>
        </div>

        <p className="mt-24 text-justify lg:text-lg">
          You are now browsing the 2.0-beta version, content will be added very
          soon. Feel free to provide feedback by creating new{' '}
          <a href="https://github.com/exnight/exnight.github.io/issues">
            <u>issues</u>
          </a>{' '}
          on the GitHub repository.
        </p>
      </div>
    </>
  );
};

export default MainFrame;
